<html>
<head>
    <title>Create</title>
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <script type="text/javascript" src="/js/funcs.js"></script>
    </head>
<body>
<textarea id="code_snippet"></textarea>
<div>
    <span>Time restriction:</span>
    <input id="time_restriction" type="text"/>
</div>
<div>
    <span>Views restriction:</span>
    <input id="views_restriction" type="text"/>
</div>
<button id="send_snippet" type="submit" onclick="send()">Submit</button>
</body>
</html>